application: bookmarkthisway
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /libs
  static_dir: web/libs

- url: .*
  script: web/index.html
